version: "3.9"
services:
  backend:
    build: ../server
    env_file:
      - ../.env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ../server:/app
    command: npm run dev
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: